name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name'
        required: true
      repoName:
        description: 'Repo name'
        required: true

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - id: fetch_tarball_url
        name: Fetch target release URL by tag
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/milvus-io/${{ github.event.inputs.repoName }}/releases/tags/${{ github.event.inputs.tagName }}" \
            | jq -r '.tarball_url' \
            > ./tarball_url
          export release_url=`cat ./tarball_url`
          echo "::set-output name=tarball_url::$release_url"
          echo "=>Completed: Fetching target release URL $release_url"
      - id: download_code
        name: Download and untar release code
        run: |
          wget "${{ steps.fetch_tarball_url.outputs.tarball_url }}" -O "${{ github.event.inputs.repoName }}.tar.gz"
          sudo mkdir "./${{ github.event.inputs.repoName }}"
          sudo tar -xzvf "${{ github.event.inputs.repoName }}.tar.gz" -C "${{ github.event.inputs.repoName }}" --strip-components 1
          echo "=>List all files"
          ls -l "./${{ github.event.inputs.repoName }}"
          echo "=>Completed: Download and untar."
      - id: update_repo_directory
        name: Git clone and update API reference doc directory
        run: |
          sudo git clone https://.:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git config --global user.email "zhen.chen@zilliz.com"
          git config --global user.name "czhen-zilliz" 
          sudo chmod -R 777 ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
          if [ ! -d "./APIReference" ]
          then
          echo "=>No APIReference directory, create it."
            mkdir APIReference
          fi
          cd APIReference
          if [ ! -d "./${{ github.event.inputs.repoName }}" ]
          then
            echo "=>No ${{ github.event.inputs.repoName }} doc directory, create it."
            mkdir ${{ github.event.inputs.repoName }}
          fi
          cd ../../
          echo "=>Completed: Git clone and update API reference doc directory."
      - id: update_repo_pymilvus
        name: Update pymilvus doc repo
        if: ${{ github.event.inputs.repoName == 'pymilvus' }}
        run: |
          sudo chmod -R 777 ${{ github.event.inputs.repoName }}
          cd ${{ github.event.inputs.repoName }}
          sudo apt update
          sudo apt install python3
          sudo apt install python3-pip
          python3 --version
          pip3 --version
          pip3 download -r requirements.txt
          pip3 install -r requirements.txt -U --force-reinstall
          cd docs
          sudo apt install make
          make html
          cd ../../
          # sudo git clone https://.:${{ secrets.ACCESS_TOKEN }}@github.com/czhen-zilliz/action-test.git
          # git config --global user.email "zhen.chen@zilliz.com"
          # git config --global user.name "czhen-zilliz" 
          # sudo chmod -R 777 action-test
          cd ${{ github.event.repository.name }}/APIReference/pymilvus
          echo "Upcomming tag name: ${{ github.event.inputs.tagName }}"
          echo "=>List all doc versions"
          ls -l
          if [ -d "./${{ github.event.inputs.tagName }}" ]
          then
            echo "===tag name exists, remove all under this dir==="
            sudo rm -fr "./${{ github.event.inputs.tagName }}"
          else
            echo "===miss tag name, create this dir==="
            sudo mkdir "./${{ github.event.inputs.tagName }}"
          fi
          sudo cp -r ../../../pymilvus/docs/build/html "./${{ github.event.inputs.tagName }}"
         
